# Site settings
dir: rtl
title: Souilah Rezak Blog
SEOTitle: Souilah Blog
header-img: img/home-bg.jpg
email: rezazsouilah@gmail.com
description:  Web & Mobile Lover，Software Engineer，UX Designer | "
keyword: huxpro, @huxpro, , Hux Blog, , Web, JavaScript"
url: "https://rezaksouilah.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
email: rezazsouilah@gmail.com
github_username:    rezaksouilah
twitter_username:   RezakSouilah
facebook_username: rezak.souilah.5
linkedin_username:  souilah-rezak-ens-kouba-b01336176




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: hux

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Rezak Souilah <br> Enseignant chercher à l'université Yahia Fares, Médéa"
sidebar-avatar: /img/souilah.png  # use absolute URL, seeing it's used in both `/` and `/about/`



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    title: "Hocine Ayadi",
    #     href: ""
    # },{
      # title: "Rezak Souilah",
        href: ""
    },{
       # title: "Hamza Souilah",
        href: "https://sherrywoo.me/"
    }
]
